Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proyecto_TiendaElectronica.Models;
using Proyecto_TiendaElectronica.ModelBinder;
using Microsoft.AspNetCore.Identity;
using Proyecto_TiendaElectronica.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Proyecto_TiendaElectronica.ModelBinders;
using QuestPDF.Infrastructure;
using QuestPDF.Fluent;
using QuestPDF.Infrastructure;

namespace Proyecto_TiendaElectronica.Controllers
{
    public class AdminController : Controller
    {
        private readonly AppDBContext _context;
        private readonly UserManager<Usuario> _userManager;
        private readonly SignInManager<Usuario> _signInManager;

        public AdminController(AppDBContext context, UserManager<Usuario> userManager, SignInManager<Usuario> signInManager) { 
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            QuestPDF.Settings.License = LicenseType.Community;
        }

		[Authorize(Roles = "Administrador")]
		public ActionResult Index()
		{
			ViewBag.Pagina = "Index";
			return View();
		}

        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Articulos()
		{

			var articulos = await _context.Articulo.Include("Categoria").Include("Imagen").Take(10).ToListAsync();
			ViewBag.Pagina = "Articulos";

			return View(articulos);

		}

        [Authorize(Roles = "Administrador")]


        public ActionResult CrearArticulo()
		{

			var categorias = _context.Categoria.ToList();

			ViewBag.Categorias = new SelectList(categorias, "CategoriaId", "Nombre");

			ViewBag.Pagina = "CrearArticulo";

			return View();
		}


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CrearArticulo([ModelBinder(BinderType = typeof(ArticuloModelBinder), Name = "CustomBinderForCreate")] Articulo articulo)
        {

          
            try
            {
                _context.Articulo.Add(articulo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Articulos));
            }
            catch (DbUpdateException)
            {
                TempData["SweetAlertScript"] = "<script>Swal.fire({ title: \"Error\", text: \"Error al guardar el artículo. Por favor, inténtelo más tarde.\", icon: \"error\", confirmButtonColor: \"#E14848\" });</script>";
            }
            catch (Exception)
            {
                TempData["SweetAlertScript"] = "<script>Swal.fire({ title: \"Error\", text: \"Ha ocurrido un error. Por favor, inténtelo más tarde.\", icon: \"error\", confirmButtonColor: \"#E14848\" });</script>";
            }

            return View(articulo);
        }



        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> VerArticulo(int id)
		{
			if (id == null)
			{
				return NotFound();
			}
			try
			{
				var articulo = await _context.Articulo.FindAsync(id);
				if (articulo == null)
				{
					return NotFound();
				}

				var imagen = await _context.Imagen.FindAsync(articulo.codigoImagen);
				var categoria = await _context.Categoria.FindAsync(articulo.idCategoria);

				ViewBag.Imagen1 = imagen.Imagen1;
				ViewBag.Imagen2 = imagen.Imagen2;
				ViewBag.Imagen3 = imagen.Imagen3;

				ViewBag.Categoria = categoria.Nombre.ToString();


				return View(articulo);
			}
			catch (Exception)
			{
				return RedirectToAction(nameof(Articulos));
			}
		}

		[HttpGet]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> EditarArticulo(int id)
		{
			var articulo = await _context.Articulo.FindAsync(id);
			if (articulo == null)
			{
				return NotFound();
			}



			var categorias = _context.Categoria.ToList();
			ViewBag.Categorias = new SelectList(categorias, "CategoriaId", "Nombre");

            return View(articulo);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> EditarArticulo(Articulo articulo)
		{
			Articulo articuloDB = new Articulo
			{
				ArticuloId = articulo.ArticuloId,
				Nombre = articulo.Nombre,
				Descripcion = articulo.Descripcion,
				Marca = articulo.Marca,
				Precio = articulo.Precio,
				Cantidad = articulo.Cantidad,
				idCategoria = articulo.idCategoria,
				codigoImagen = articulo.codigoImagen,
			};



			try
			{
				_context.Articulo.Update(articuloDB);
				await _context.SaveChangesAsync();


				return RedirectToAction(nameof(Articulos));
			}

			catch (Exception)
			{
				return View(articuloDB);
			}

		}
		[HttpGet]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> ModificaImagen(int codigoImagen, int ArticuloID)
		{
			var Imagen = await _context.Imagen.FindAsync(codigoImagen);

			if (Imagen == null)
			{
				return NotFound();
			}
			ViewBag.ArticuloId = ArticuloID;
            ViewBag.Pagina = "ModificaImagen";
            return View(Imagen);
		}

		[HttpPost]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> ModificaImagen(Imagen imagen, IFormFile Imagen1, IFormFile Imagen2, IFormFile Imagen3)
		{

			var Imagen = await _context.Imagen.FindAsync(imagen.ImagenId);
			if (Imagen1 != null)
			{
				using (var memoryStream = new MemoryStream())
				{
					await Imagen1.CopyToAsync(memoryStream);
					Imagen.Imagen1 = memoryStream.ToArray();
				}
			}

			if (Imagen2 != null)
			{
				using (var memoryStream = new MemoryStream())
				{
					await Imagen2.CopyToAsync(memoryStream);
					Imagen.Imagen2 = memoryStream.ToArray();
				}
			}

			if (Imagen3 != null)
			{
				using (var memoryStream = new MemoryStream())
				{
					await Imagen3.CopyToAsync(memoryStream);
					Imagen.Imagen3 = memoryStream.ToArray();
				}
			}

			_context.Update(Imagen);
			await _context.SaveChangesAsync();
			return RedirectToAction("Articulos");

		}

		[HttpGet]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> EliminarArticulo(int id)
		{
			if (id == null)
			{
				return Json(new { success = false, message = "ID de Articulo no proporcionado." });
			}

			try
			{
				var articulo = await _context.Articulo.FindAsync(id);

				if (articulo == null)
				{
					return Json(new { success = false, message = "articulo no encontrado." });
				}
				_context.Articulo.Remove(articulo);

				_context.SaveChanges();

				return Json(new { success = true, message = "Articulo eliminado con éxito." });
			}
			catch (Exception)
			{
				return Json(new { success = false, message = "Ocurrió un error al eliminar el articulo." });
			}



		}


		[HttpGet]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Usuarios()
		{

			var usuarios = await _context.Usuario.ToListAsync();
			var datos = new List<UserViewModel>();

			foreach (var usuario in usuarios) {
				var roles = await _userManager.GetRolesAsync(usuario);

				var rol = roles.FirstOrDefault();

				var user = Conversion(usuario, rol);

				datos.Add(user);
			}

			ViewBag.Pagina = "Usuarios";

			return View(datos);

		}


		[HttpGet]
        [Authorize(Roles = "Administrador")]
        public IActionResult CrearUsuario()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CrearUsuario(UserViewModel model)
		{

			if (ModelState.IsValid)
			{
				var usuario = new Usuario { Id = model.UsuarioId, UserName = model.Nombre, Email = model.Correo, PhoneNumber = model.Telefono, State = model.Estado };

				var result = await _userManager.CreateAsync(usuario, model.Contrasena);

				if (result.Succeeded)
				{

					await _userManager.AddToRoleAsync(usuario, model.Rol);

					return RedirectToAction("Usuarios");
				}

				foreach (var error in result.Errors)
				{
					ModelState.AddModelError("", error.Description);
				}

			}

			return View(model);


		}


		[HttpGet]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> VerUsuario(string id)
		{
			if (id == null)
			{
				return NotFound();
			}

			try
			{
				var usuario = await _context.Usuario.FindAsync(id);

				if (usuario == null)
				{
					return NotFound();
				}

				var roles = await _userManager.GetRolesAsync(usuario);

				var rol = roles.FirstOrDefault();

				var user = Conversion(usuario, rol);

				return View(user);
			}
			catch (Exception)
			{
				return RedirectToAction(nameof(Usuarios));
			}


		}

		[HttpGet]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> EditarUsuario(string id)
		{
			if (id == null)
			{
				return NotFound();
			}


			try
			{
				var usuario = await _context.Usuario.FindAsync(id);

				if (usuario == null)
				{
					return NotFound();
				}

				var roles = await _userManager.GetRolesAsync(usuario);

				var rol = roles.FirstOrDefault();

				var user = Conversion(usuario, rol);

				return View(user);
			}
			catch (Exception)
			{
				return RedirectToAction(nameof(Usuarios));
			}


		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> EditarUsuario([ModelBinder(BinderType = typeof(ModelBinder.UsuarioModelBinder))] UserViewModel model)
		{

			if (ModelState.IsValid)
			{
				var usuario = await _userManager.FindByIdAsync(model.UsuarioId);

				if (usuario == null) {
					return NotFound();
				}

				usuario.State = model.Estado;
				usuario.UserName = model.Nombre;
				usuario.Email = model.Correo;
				usuario.PhoneNumber = model.Telefono;

				var result = await _userManager.UpdateAsync(usuario);

				if (result.Succeeded)
				{
					var rolActual = await _userManager.GetRolesAsync(usuario);

					await _userManager.RemoveFromRolesAsync(usuario, rolActual);

					await _userManager.AddToRoleAsync(usuario, model.Rol);

					return RedirectToAction("Usuarios");
				}

				foreach (var error in result.Errors)
				{

Controllers/LogueoController.cs
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Proyecto_TiendaElectronica.ViewModels;
using Proyecto_TiendaElectronica.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;


namespace Proyecto_TiendaElectronica.Controllers
{
    public class LogueoController : Controller
    {
        private readonly AppDBContext _context;
        private readonly UserManager<Usuario> _userManager;
        private readonly SignInManager<Usuario> _signInManager;

        public LogueoController(AppDBContext context, UserManager<Usuario> userManager, SignInManager<Usuario> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Index() {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(UserLogin model) {
            if (ModelState.IsValid) {
                var user = await _userManager.FindByNameAsync(model.UserName);

                if (user != null)
                {

                    if (!user.State)
                    {
                        TempData["SweetAlertScript"] = "<script>Swal.fire({\r\n  title: \"Error\",\r\n  text: \"El estado del usuario es inactivo.\",\r\n  icon: \"error\"\r\n, confirmButtonColor: \"#E14848\"});;</script>";
                        return View(model);
                    }

                    if (await _userManager.IsLockedOutAsync(user))
                    {
                        TempData["SweetAlertScript"] = "<script>Swal.fire({\r\n  title: \"Error\",\r\n  text: \"Su cuenta de usuario esta bloqueada.\",\r\n  icon: \"error\"\r\n, confirmButtonColor: \"#E14848\"});;</script>";
                        return View(model);
                    }

                    var result = await _signInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, lockoutOnFailure: true);

                    if (result.Succeeded)
                    {
                        var usuario = await _userManager.FindByNameAsync(model.UserName);

                        var roles = await _userManager.GetRolesAsync(usuario);

                        var rol = roles.FirstOrDefault();


                        return RedirectToAction("Index", "Home");



                    }
                    else if (!result.IsNotAllowed)
                    {
                        TempData["SweetAlertScript"] = "<script>Swal.fire({\r\n  title: \"Error\",\r\n  text: \"El usuario o la contraseña no coinciden.\",\r\n  icon: \"error\"\r\n, confirmButtonColor: \"#E14848\"});;</script>";
                    }
                    else
                    {
                        ModelState.AddModelError("", "No se pudo realizar el inicio de sesión, por favor intentelo más tarde.");
                        TempData["SweetAlertScript"] = "<script>Swal.fire({\r\n  title: \"Error\",\r\n  text: \"No se pudo realizar el inicio de sesión, por favor reintentelo más tarde.\",\r\n  icon: \"error\"\r\n, confirmButtonColor: \"#E14848\"});;</script>";
                    }
                }else{
                    TempData["SweetAlertScript"] = "<script>Swal.fire({\r\n  title: \"Error\",\r\n  text: \"El usuario de usuario ingresado no existe.\",\r\n  icon: \"error\"\r\n, confirmButtonColor: \"#E14848\"});;</script>";
                }
            }

            return View(model);
        }

        public async Task<IActionResult> Logout() {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Registro() {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registro(UserRegister model) {
            if (ModelState.IsValid) {
                var usuario = new Usuario { Id = model.UsuarioId, UserName = model.Nombre, Email = model.Correo, PhoneNumber = model.Telefono, State = true };

                try
                {
                    var result = await _userManager.CreateAsync(usuario, model.Contrasena);

                    if (result.Succeeded)
                    {

                        await _userManager.AddToRoleAsync(usuario, "Usuario");

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            if (error.Code == "DuplicateUserName")
                            {
                                ModelState.AddModelError("", "No se pudo realizar el registro del usuario, por favor intentelo más tarde.");
                                TempData["SweetAlertScript"] = "<script>Swal.fire({\r\n  title: \"Error\",\r\n  text: \"No se pudo realizar el registro, el nombre de usuario ingresado ya esta registrado. Por favor ingrese un nombre de usuario diferente.\",\r\n  icon: \"error\"\r\n, confirmButtonColor: \"#E14848\"});;</script>";
                            }
                            else
                            {
                                ModelState.AddModelError("", error.Description);
                                TempData["SweetAlertScript"] = "<script>Swal.fire({\r\n  title: \"Error\",\r\n  text: \"No se pudo realizar el registro. Por favor reintentelo más tarde.\",\r\n  icon: \"error\"\r\n, confirmButtonColor: \"#E14848\"});;</script>";
                            }
                        }




                    }
                }
                catch (DbUpdateException ex)
                {
                    if (ex.InnerException != null && ex.InnerException.Message.Contains("restricción PRIMARY KEY"))
                    {
                        TempData["SweetAlertScript"] = "<script>Swal.fire({\r\n  title: \"Error\",\r\n  text: \"No se pudo realizar el registro. El usuario con la cédula '" + model.UsuarioId + "' ya sido registrado anteriormente. Por favor ingrese un nuevo número de cédula.\",\r\n  icon: \"error\"\r\n, confirmButtonColor: \"#E14848\"});;</script>";
                    }
                    else {
                        TempData["SweetAlertScript"] = "<script>Swal.fire({\r\n  title: \"Error\",\r\n  text: \"No se pudo realizar el registro. Por favor reintentelo más tarde.\",\r\n  icon: \"error\"\r\n, confirmButtonColor: \"#E14848\"});;</script>";
                    }
                    
                }
                catch (Exception ex) {
                    TempData["SweetAlertScript"] = "<script>Swal.fire({\r\n  title: \"Error\",\r\n  text: \"No se pudo realizar el registro. Por favor reintentelo más tarde.\",\r\n  icon: \"error\"\r\n, confirmButtonColor: \"#E14848\"});;</script>";
                }
                

            }

            return View(model);

        }
    }
}

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto_TiendaElectronica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/adminStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/formStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proyecto_TiendaElectronica.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.css" />

    @if (ViewBag.Pagina == "CrearArticulo" || ViewBag.Pagina == "ModificaImagen")
    {
        <script src="~/js/imagePreview.js"></script>
        
    }

</head>
<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Navatech Administración</h3>
            </div>

            <ul class="list-unstyled components">
                <li class="
                    @(ViewBag.Pagina == "Index" ? "active" : "" )
                ">
                    <a href="@Url.Action("Index")">
                        <div class="d-flex">
                            <div style="margin-right: 18px">
                                <i class="fa-solid fa-house"></i>
                            </div>
                            <div class="mx-2">
                                Inicio
                            </div>

                        </div>
                    </a>
                </li>
                <li class="
                    @(ViewBag.Pagina == "Usuarios" ? "active" : "" )
                ">
                    <a href="@Url.Action("Usuarios")">
                        <div class="d-flex">
                            <div style="margin-right: 18px">
                                <i class="fa-solid fa-user"></i>
                            </div>
                            <div class="mx-2">
                                Usuarios
                            </div>

                        </div>
                    </a>
                </li>
                <li class="
                    @(ViewBag.Pagina == "Articulos" ? "active" : "" )
                ">
                    <a href="@Url.Action("Articulos")">
                        <div class="d-flex">
                            <div style="margin-right: 10px">
                                <i class="fa-solid fa-laptop"></i>
                            </div>
                            <div class="mx-2">
                                Artículos
                            </div>

                        </div>
                    </a>
                </li>
                <li class="
                    @(ViewBag.Pagina == "Facturas" ? "active" : "" )
                ">
                    <a href="@Url.Action("Factura")">
                        <div class="d-flex">
                            <div style="margin-right: 18px">
                                <i class="fa-solid fa-file-invoice"></i>
                            </div>
                            <div class="mx-2">
                                Facturas
                            </div>

                        </div>
                    </a>
                </li>
                <li>
                    <div>
                        <a href="#homeSubmenu" data-bs-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                                <i class="fa-solid fa-user-lock" style="margin-right: 10px"></i>
                                Sesión
                        </a>
                        <ul class="collapse list-unstyled" id="homeSubmenu">
                            <li>
                                <a href="@Url.Action("Perfil", "Home")">
                                    <div class="d-flex">
                                        <div style="margin-right: 5px">
                                            <i class="fa-solid fa-user"></i>
                                        </div>
                                        <div class="mx-2">
                                            Mi Perfil
                                        </div>

                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Home")">
                                    <div class="d-flex">
                                        <div style="margin-right: 5px">
                                            <i class="fa-solid fa-arrow-left-long"></i>
                                        </div>
                                        <div class="mx-2">
                                            Vista Cliente
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Logout", "Logueo")">
                                    <div class="d-flex">
                                        <div style="margin-right: 5px">
                                            <i class="fa-solid fa-right-from-bracket"></i>
                                        </div>
                                        <div class="mx-2">
                                            Cerrar Sesión
                                        </div>

                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                    
                </li>
            </ul>

            
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn bars">
                        <i class="fa-solid fa-bars"></i>
                    </button>

                    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
                        <h1>Navatech</h1>
                    </div>
                </div>
            </nav>

            <div class="">
                <main role="main" class="">
                    @RenderBody()
                </main>
            </div>

        </div>
    </div>





    

    

   

    

    <script src="https://kit.fontawesome.com/2425b0cf01.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.20.1/jquery.validate.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @if (ViewBag.Pagina == "Usuarios" || ViewBag.Pagina == "Articulos" || ViewBag.Pagina == "Facturas")
    {
        
        <script src="~/js/site.js" asp-append-version="true"></script>
    }

    @if (ViewBag.Pagina == "Index")
    {
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script src="~/js/Graficos.js" asp-append-version="true"></script>
    }
    @await RenderSectionAsync("Scripts", required: false)


    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>


</body>

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto_TiendaElectronica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/loginStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/formStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proyecto_TiendaElectronica.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body style="background-color: #010101">
    <div class="row" style="--bs-gutter-x: 0rem;">
        <div class="col-lg-4 col-md-4 col-sm-4">
            <img src="/img/logueo.jpg" alt="Alternate Text" style="width:100%; height:100vh" />
        </div>
        <div class="col-xl-8 col-md-8 col-sm-8 d-flex align-items-center">
            <div class="container  justify-content-center" style="margin-left: 30%; margin-right: 30%;">
                <main role="main">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
   

    <script src="https://kit.fontawesome.com/2425b0cf01.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.20.1/jquery.validate.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>